# Generated by Django 4.0.5 on 2022-09-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_description_size_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='colorName',
            new_name='sizeName',
        ),
    ]
