# Generated by Django 4.0.5 on 2022-09-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_colorname_size_sizename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='name',
            new_name='detailName',
        ),
    ]
